### ISSUE TITLE
Compilation instructions?

### ISSUE THREAD

**Issue by PaulBatchelor** [boomlinde/gobassline#2]
I don't see any compilation instructions anywhere. How does one compile this, and what are the dependencies?

**Comment by boomlinde** [comment]
Hi Paul,
This follows a typical Go workflow. Assuming that you have go (1.4 or newer) installed:
1. Set up the `GOPATH` environment variable to e.g. `/home/username/devel/go`
2. Issue `go get github.com/boomlinde/acidforth`. This will download and build the package along with its Go dependencies into the GOPATH directory tree. Once built, the acidforth binary can be found in `$GOPATH/bin`

The project depends on two other Go packages, `code.google.com/p/portaudio-go/portaudio` and `github.com/rakyll/portmidi`. These require the portaudio and portmidi libraries and headers respectively as they will create C bindings with `pkg-config portaudio-2.0` and `-lportmidi`. These libraries are not automatically downloaded. On the development system (OSX 10.10.5) I got these via the brew package manager.

Go is quite a hack when it comes to linking to external libraries, see https://golang.org/cmd/cgo/. Chances are that you will have to tweak the `cgo` magic comments to get them to build for a specific system.

I'll add this information to the README some time this week, but let me know if you need assistance with a particular operating system and I can give it a try in a VM. My next goal is to provide binaries for Windows.

**Comment by boomlinde** [comment]
Build instructions added to the README in 21c81307c82f78d0cdb8af492e7f0a3617094fa1
